feat: wait deploy finish to complete the pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -180,3 +180,39 @@ jobs:
             --data-urlencode "forge_deploy_commit=${{ github.sha }}" \
             --data-urlencode "forge_deploy_author=${{ github.actor }}" \
             --data-urlencode "forge_deploy_message=${{ steps.get_commit_message.outputs.message }}"
+      - name: Wait for deployment to complete
+        run: |
+          MAX_ATTEMPTS=20
+          ATTEMPT=0
+          STATUS="in_progress"
+          LATEST_COMMIT="${{ github.sha }}"
+
+          while [[ "$STATUS" == "in_progress" || "$STATUS" == "null" ]] && [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
+            echo "Checking deployment status (Attempt $((ATTEMPT+1))/$MAX_ATTEMPTS)..."
+
+            RESPONSE=$(curl -s -X GET \
+              "https://forge.laravel.com/api/v1/servers/${{ secrets.FORGE_SERVER_ID }}/sites/${{ secrets.FORGE_SITE_ID }}/deployment-history" \
+              -H "Authorization: Bearer ${{ secrets.FORGE_API_TOKEN }}" \
+              -H "Accept: application/json")
+
+            LATEST_DEPLOYMENT=$(echo "$RESPONSE" | jq -r --arg LATEST_COMMIT "$LATEST_COMMIT" '.deployments[] | select(.commit_hash == $LATEST_COMMIT) | .status')
+
+            STATUS=$LATEST_DEPLOYMENT
+
+            if [[ "$STATUS" == "finished" ]]; then
+              echo "Deployment completed successfully."
+              exit 0
+            elif [[ "$STATUS" == "failed" ]]; then
+              echo "Deployment failed!"
+              exit 1
+            else
+              echo "Deployment is still in progress..."
+              ATTEMPT=$((ATTEMPT + 1))
+              sleep 15
+            fi
+          done
+
+          if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
+            echo "Deployment timed out after $MAX_ATTEMPTS attempts."
+            exit 1
+          fi
